---
project_name: gaia

release:
  github:
    owner: marbar3778
    name: gaia

builds:
  - binary: gaiad
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    main: ./cmd/gaiad/
    flags:
      - -tags=netgo,ledger
    ldflags: -s -w - trimpath -X github.com/cosmos/cosmos-sdk/version.Name=gaia -X github.com/cosmos/cosmos-sdk/version.ServerName=gaiad -X github.com/cosmos/cosmos-sdk/version.ClientName=gaiacli -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"

  - binary: gaiacli
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    main: ./cmd/gaiacli/
    ldflags: -s -w - trimpath -X github.com/cosmos/cosmos-sdk/version.Name=gaia -X github.com/cosmos/cosmos-sdk/version.ServerName=gaiad -X github.com/cosmos/cosmos-sdk/version.ClientName=gaiacli -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
