---
project_name: gaia

release:
  github:
    owner: marbar3778
    name: gaia

builds:
  - binary: gaiad
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    main: ./cmd/gaiad/
    ldflags: -s -w - trimpath -X github.com/cosmos/cosmos-sdk/version.Name=gaia -X github.com/cosmos/cosmos-sdk/version.ServerName=gaiad -X github.com/cosmos/cosmos-sdk/version.ClientName=gaiacli -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"
  - binary: gaiacli
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    main: ./cmd/gaiacli/
    ldflags: -s -w - trimpath -X github.com/cosmos/cosmos-sdk/version.Name=gaia -X github.com/cosmos/cosmos-sdk/version.ServerName=gaiad -X github.com/cosmos/cosmos-sdk/version.ClientName=gaiacli -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^dev:"
      - "README"
      - Merge pull request
      - Merge branch

dockers:
  - dockerfile: build/Dockerfile
    binaries:
      - golangci-lint
    image_templates:
      - "golangci/golangci-lint:latest"
      - "golangci/golangci-lint:{{ .Tag }}"
      - "golangci/golangci-lint:v{{ .Major }}.{{ .Minor }}"
  - dockerfile: build/Dockerfile.alpine
    binaries:
      - golangci-lint
    image_templates:
      - "golangci/golangci-lint:latest-alpine"
      - "golangci/golangci-lint:{{ .Tag }}-alpine"
      - "golangci/golangci-lint:v{{ .Major }}.{{ .Minor }}-alpine"

brews:
  - github:
      owner: golangci
      name: homebrew-tap
    folder: Formula
    homepage: https://golangci.com
    description: Fast linters runner for Go.
    install: |
      bin.install "golangci-lint"
      output = Utils.popen_read("#{bin}/golangci-lint completion bash")
      (bash_completion/"golangci-lint").write output
      output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
      (zsh_completion/"_golangci-lint").write output
      prefix.install_metafiles
    test: |
      system "#{bin}/golangci-lint --version"
